### ISSUE TITLE
[API / SCX] Upload avenant/cdi signé suite a formation

### ISSUE THREAD

**Issue by cyrilcaturani** [B3Software/api.webportage.com#48]
https://github.com/B3Software/scx.upnbiz.com/issues/634

**Comment by MichaelAntoine** [comment]
changement de version to 1.0.3

**Comment by cyrilcaturani** [comment]
@maryleneupnbiz @MichaelAntoine 

Testé en prod pour le porté "nom prénom"
J'ai utilisé le meme nom de fichier que lors de ton erreur pour etre sur que cela ne vienne pas de la : 
**PIDOLOT CASINO.pdf** (pour les espaces/min/maj)
Ça fonctionne.


**Pour la recette**, j'ai eu la même erreur, c'était un problème de droits d’écriture sur un répertoire. C'est corrigé, testé avec belkir et ok


@MichaelAntoine : pour info, le répertoire public/tmp/files

![image](https://cloud.githubusercontent.com/assets/2923039/6438117/70ed8194-c0c6-11e4-87df-b266228c6042.png)

**Comment by MichaelAntoine** [comment]
ok.. donc le problème a été résolue lors de la MEP 1.0.1 (27/02/2015)
